name = "dialoguemaker/use_pages"
version = "0.1.0-patch-4"
description = ""
authors = ["Christian Toney <christian.toney@beastslash.com>"]
repository = "https://github.com/DialogueMaker/use_pages"
license = "GPL-3.0"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**/*.lua",
]

[target]
environment = "roblox"
lib = "src/init.lua"
build_files = ["src"]

[engines]
pesde = "^0.7.0-rc.3"
lune = "^0.8.9"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
darklua = { name = "pesde/darklua", version = "^0.16.0", target = "lune" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.47.0", target = "lune" }

[peer_dependencies]
react = { wally = "jsdotlua/react", version = "^17.2.1" }

[dependencies]
dialogue_types = { name = "dialoguemaker/dialogue_types", version = "^0.1.0-patch-7" }
effect_types = { name = "dialoguemaker/effect_types", version = "^0.1.0-patch-9" }
theme_types = { name = "dialoguemaker/theme_types", version = "^0.1.0-patch-6" }
dialogue_content_fitter = { name = "dialoguemaker/dialogue_content_fitter", version = "^0.1.0-patch-2" }
