[package]
name = "dialoguemaker/use-pages"
version = "0.1.0-patch-1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/DialogueMaker/use-pages"
authors = ["Christian Toney <christian.toney@beastslash.com>"]
include = ["src", "src/**/*.lua", "wally.toml", "default.project.json"]
exclude = ["**"]

[dependencies]
dialogue-content-fitter = "dialoguemaker/dialogue-content-fitter@0.1.0-patch-1"
dialogue-types = "dialoguemaker/dialogue-types@0.1.0-patch-2"
effect-types = "dialoguemaker/effect-types@0.1.0-patch-3"
react = "jsdotlua/react@17.2.1"
theme-types = "dialoguemaker/theme-types@0.1.0-patch-1"